=begin
#Kubernetes

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1.13.13

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.1.0

=end

module Kubernetes
  VERSION = '1.13.13-alpha'
end
