=begin
#Kubernetes

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: release-1.32

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.1.0

=end

module Kubernetes
  VERSION = '1.32.6'
end
