# -*- encoding: utf-8 -*-

=begin
#Kubernetes

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: release-1.31

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.1.0

=end

$:.push File.expand_path("../lib", __FILE__)
require "kubernetes/version"

Gem::Specification.new do |s|
  s.name        = "kubernetes"
  s.version     = Kubernetes::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["Kubernetes authors"]
  s.email       = ["kubernetes-sig-api-machinery@googlegroups.com"]
  s.homepage    = "https://kubernetes.io"
  s.summary     = "Kubernetes ruby client."
  s.description = "Kubernetes official ruby client to talk to kubernetes clusters."
  s.license     = "Apache V2"
  s.required_ruby_version = ">= 2.4"

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib", "src"]
end
